server:
  port: 8888
spring:
  devtools:
    restart:
      enabled: true #热部署
  datasource:
    url: jdbc:mysql://localhost/shuizhi?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: 123456
  mvc:
    static-path-pattern: /*
mybatis:
  mapper-locations: classpath:com/shuizhi/dao/mapping/*.xml
